import { useState, useEffect, useMemo, useCallback, useRef } from 'react'
import { motion, useReducedMotion } from 'framer-motion'
import { WidgetCard } from '@/components/widgets/WidgetCard'
import { StatTile } from '@/components/shared/StatTile'
import { EmptyState } from '@/components/shared/EmptyState'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import { Chip } from '@/components/ui/chip'
import { useStore, readStore, writeStore } from '@/lib/store'
import { localDate, getWeekDates } from '@/lib/date-utils'
import { foodBudgetForMonth, foodSpentPrimary, withFoodSpent, withFoodBudget, sumMarket, type FinanceDataLike } from '@/lib/food-budget'
import {
  Plus,
  Trash2,
  ShoppingCart,
  TrendingUp,
  Store,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  X,
  Pencil,
  Bookmark,
  Square,
  CheckSquare,
} from 'lucide-react'
import type { MarketPreset, MarketList } from '@/types/gym'
import { DEFAULT_MARKET_PRESETS } from '@/types/gym'

// ── Types ────────────────────────────────────────────────────────────────────

interface GroceryItem {
  id: string
  name: string
  price: number
  quantity: number
  store: string
  category: string
}

interface WeeklyMarketLog {
  weekStart: string
  items: GroceryItem[]
}

// ── Helpers ──────────────────────────────────────────────────────────────────

const STORES = ['D1', 'Carulla', 'Exito', 'Rappi', 'Other']
const CATEGORIES = ['Protein', 'Carbs', 'Snacks', 'Dairy', 'Produce', 'Hygiene', 'Other']
const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

const fmtCOP = (n: number) => {
  if (Math.abs(n) >= 1_000_000) return `$${(n / 1_000_000).toFixed(1)}M`
  if (Math.abs(n) >= 1_000) return `$${Math.round(n / 1_000)}K`
  return `$${n}`
}
const fmtFull = (n: number) => `$${n.toLocaleString('es-CO')}`

/** Short/relative label for an ISO timestamp */
function fmtRelDate(iso: string): string {
  const d = new Date(iso)
  if (isNaN(d.getTime())) return ''
  const diffDays = Math.floor((Date.now() - d.getTime()) / 86_400_000)
  if (diffDays <= 0) return 'today'
  if (diffDays === 1) return 'yesterday'
  if (diffDays < 7) return `${diffDays}d ago`
  return `${d.getDate()} ${MONTHS[d.getMonth()]}`
}

/** Get all Monday dates for weeks in a given month */
function getWeeksInMonth(year: number, month: number): string[] {
  const weeks: string[] = []
  const d = new Date(year, month, 1)
  // Go to the Monday of the week containing the 1st
  const day = d.getDay()
  d.setDate(d.getDate() - ((day + 6) % 7))
  while (true) {
    const weekStart = localDate(d)
    // Include this week if any day falls in our target month
    const weekEnd = new Date(d)
    weekEnd.setDate(d.getDate() + 6)
    if (d.getMonth() > month && d.getFullYear() >= year) break
    if (weekEnd.getMonth() >= month || weekEnd.getFullYear() > year || d.getMonth() === month || weekEnd.getMonth() === month) {
      weeks.push(weekStart)
    }
    d.setDate(d.getDate() + 7)
    if (weeks.length > 6) break // safety
  }
  return weeks
}

function getWeekLabel(weekStart: string): string {
  const start = new Date(weekStart + 'T00:00:00')
  const end = new Date(start)
  end.setDate(start.getDate() + 6)
  const fmt = (d: Date) => `${d.getDate()} ${MONTHS[d.getMonth()]}`
  return `${fmt(start)} – ${fmt(end)}`
}

// ── Component ────────────────────────────────────────────────────────────────

export function MarketLog() {
  const reduceMotion = useReducedMotion()
  const today = localDate()
  const todayWeekStart = getWeekDates(today)[0]

  // Current view state
  const now = new Date()
  const [viewYear, setViewYear] = useState(now.getFullYear())
  const [viewMonth, setViewMonth] = useState(now.getMonth())
  const [selectedWeek, setSelectedWeek] = useState(todayWeekStart)

  const weeksInMonth = useMemo(() => getWeeksInMonth(viewYear, viewMonth), [viewYear, viewMonth])

  // Data for selected week
  const [log, setLogState] = useState<WeeklyMarketLog>({ weekStart: selectedWeek, items: [] })
  const [budget, setBudget] = useStore<number>('cortex-market-budget', 646000)
  const [editingBudget, setEditingBudget] = useState(false)
  const [budgetInput, setBudgetInput] = useState('')
  // The Finances Food budget is the single source of truth; Market spend rolls up into it.
  const [finances, setFinances] = useStore<FinanceDataLike>('cortex-finances', { year: new Date().getFullYear(), items: [] })
  const backfillRan = useRef(false)

  // Suggested shopping list (generated by an MCP tool from previous buys)
  const [marketList, setMarketList] = useStore<MarketList | null>('cortex-market-list', null)

  // All weeks' data for monthly totals
  const [monthLogs, setMonthLogs] = useState<WeeklyMarketLog[]>([])

  // Load selected week
  useEffect(() => {
    readStore<WeeklyMarketLog>(`cortex-market-${selectedWeek}`, { weekStart: selectedWeek, items: [] })
      .then(setLogState)
  }, [selectedWeek])

  // Load all weeks in month for monthly total
  useEffect(() => {
    Promise.all(
      weeksInMonth.map(w => readStore<WeeklyMarketLog>(`cortex-market-${w}`, { weekStart: w, items: [] }))
    ).then(setMonthLogs)
  }, [weeksInMonth, log]) // re-fetch when current log changes

  // Live sync: the Finances Food "spent" for the viewed month = the month's market total.
  useEffect(() => {
    if (viewYear !== finances.year) return
    const total = sumMarket(monthLogs)
    if (Math.round(foodSpentPrimary(finances, viewMonth)) !== Math.round(total)) {
      setFinances(prev => withFoodSpent(prev, viewMonth, total))
    }
  }, [monthLogs, viewMonth, viewYear, finances, setFinances])

  // One-time backfill: reconcile every month of the finance year from existing market data.
  useEffect(() => {
    if (backfillRan.current || finances.items.length === 0) return
    backfillRan.current = true
    const year = finances.year
    ;(async () => {
      const done = await readStore<boolean>('cortex-food-sync-v1', false)
      if (done) return
      const totals: number[] = []
      for (let m = 0; m < 12; m++) {
        const weeks = getWeeksInMonth(year, m)
        const logs = await Promise.all(weeks.map(w => readStore<WeeklyMarketLog>(`cortex-market-${w}`, { weekStart: w, items: [] })))
        totals[m] = sumMarket(logs)
      }
      setFinances(prev => {
        let next = prev
        for (let m = 0; m < 12; m++) next = withFoodSpent(next, m, totals[m])
        return next
      })
      writeStore('cortex-food-sync-v1', true)
    })()
  }, [finances, setFinances])

  const setLog = useCallback((fn: (prev: WeeklyMarketLog) => WeeklyMarketLog) => {
    setLogState(prev => {
      const next = fn(prev)
      writeStore(`cortex-market-${selectedWeek}`, next)
      return next
    })
  }, [selectedWeek])

  const [newName, setNewName] = useState('')
  const [newPrice, setNewPrice] = useState('')
  const [newQty, setNewQty] = useState('1')
  const [newStore, setNewStore] = useState('D1')
  const [newCategory, setNewCategory] = useState('Protein')

  // Quick-add presets
  const [presets, setPresets] = useStore<MarketPreset[]>('cortex-market-presets', DEFAULT_MARKET_PRESETS)
  const [showQuickAdd, setShowQuickAdd] = useState(true)
  const [editingPresets, setEditingPresets] = useState(false)
  const [newPresetName, setNewPresetName] = useState('')
  const [newPresetPrice, setNewPresetPrice] = useState('')
  const [newPresetStore, setNewPresetStore] = useState('D1')
  const [newPresetCategory, setNewPresetCategory] = useState('Protein')

  const weeklyTotal = useMemo(() => log.items.reduce((s, item) => s + item.price * item.quantity, 0), [log.items])
  const monthlyTotal = useMemo(() => monthLogs.reduce((s, wl) => s + wl.items.reduce((ws, item) => ws + item.price * item.quantity, 0), 0), [monthLogs])
  // Budget shown = the Finances Food budget for this month (falls back to the legacy market budget).
  const foodBudget = foodBudgetForMonth(finances, viewMonth) || budget
  const byStore = useMemo(() => {
    const map = new Map<string, number>()
    for (const item of log.items) map.set(item.store, (map.get(item.store) || 0) + item.price * item.quantity)
    return Array.from(map.entries()).sort((a, b) => b[1] - a[1])
  }, [log.items])

  const byCategory = useMemo(() => {
    const map = new Map<string, number>()
    for (const item of log.items) map.set(item.category, (map.get(item.category) || 0) + item.price * item.quantity)
    return Array.from(map.entries()).sort((a, b) => b[1] - a[1])
  }, [log.items])

  const addItem = () => {
    if (!newName.trim() || !newPrice) return
    const item: GroceryItem = {
      id: Date.now().toString(),
      name: newName.trim(),
      price: Number(newPrice) || 0,
      quantity: Number(newQty) || 1,
      store: newStore,
      category: newCategory,
    }
    setLog(prev => ({ ...prev, items: [...prev.items, item] }))
    setNewName('')
    setNewPrice('')
    setNewQty('1')
  }

  const removeItem = (id: string) => {
    setLog(prev => ({ ...prev, items: prev.items.filter(i => i.id !== id) }))
  }

  const quickAddItem = (preset: MarketPreset) => {
    const item = {
      id: Date.now().toString(),
      name: preset.name,
      price: preset.price,
      quantity: preset.quantity,
      store: preset.store,
      category: preset.category,
    }
    setLog(prev => ({ ...prev, items: [...prev.items, item] }))
  }

  // ── Shopping list ─────────────────────────────────────────────────────────────
  const toggleListItem = (index: number) => {
    setMarketList(prev => prev
      ? { ...prev, items: prev.items.map((it, i) => i === index ? { ...it, checked: !it.checked } : it) }
      : prev)
  }

  const addListItemToWeek = (index: number) => {
    const li = marketList?.items[index]
    if (!li) return
    const item: GroceryItem = {
      id: 'grc-' + Date.now() + '-' + index,
      name: li.name,
      price: li.price,
      quantity: li.quantity,
      store: li.store,
      category: li.category,
    }
    setLog(prev => ({ ...prev, items: [...prev.items, item] }))
    setMarketList(prev => prev
      ? { ...prev, items: prev.items.map((it, i) => i === index ? { ...it, checked: true } : it) }
      : prev)
  }

  const clearMarketList = () => {
    setMarketList(prev => prev ? { ...prev, items: [] } : null)
  }

  const removePreset = (index: number) => {
    setPresets(prev => prev.filter((_, i) => i !== index))
  }

  const saveToPresets = () => {
    if (!newPresetName.trim() || !newPresetPrice) return
    setPresets(prev => [...prev, {
      name: newPresetName.trim(),
      price: Number(newPresetPrice),
      quantity: 1,
      store: newPresetStore,
      category: newPresetCategory,
    }])
    setNewPresetName('')
    setNewPresetPrice('')
  }

  const prevMonth = () => {
    if (viewMonth === 0) { setViewMonth(11); setViewYear(y => y - 1) }
    else setViewMonth(m => m - 1)
  }
  const nextMonth = () => {
    if (viewMonth === 11) { setViewMonth(0); setViewYear(y => y + 1) }
    else setViewMonth(m => m + 1)
  }

  return (
    <div className="mt-4 space-y-4">
      {/* Month + Week navigation */}
      <motion.div initial={reduceMotion ? false : { opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }}>
        {/* Month selector */}
        <div className="mb-3 flex items-center justify-between">
          <Button variant="ghost" size="icon-sm" onClick={prevMonth} aria-label="Previous month">
            <ChevronLeft />
          </Button>
          <span className="font-mono text-sm font-medium text-foreground">{MONTHS[viewMonth]} {viewYear}</span>
          <Button variant="ghost" size="icon-sm" onClick={nextMonth} aria-label="Next month">
            <ChevronRight />
          </Button>
        </div>

        {/* Week tabs */}
        <div className="flex gap-1.5 overflow-x-auto pb-1">
          {weeksInMonth.map((w, i) => {
            const weekTotal = monthLogs.find(ml => ml.weekStart === w)?.items.reduce((s, item) => s + item.price * item.quantity, 0) || 0
            return (
              <button
                key={w}
                onClick={() => setSelectedWeek(w)}
                aria-pressed={selectedWeek === w}
                className={`shrink-0 rounded-md border px-3 py-2 text-left transition-colors ${
                  selectedWeek === w
                    ? 'border-accent/40 bg-accent/10'
                    : 'border-border bg-card hover:bg-muted/40'
                } ${w === todayWeekStart ? 'ring-1 ring-foreground/20' : ''}`}
              >
                <p className={`font-mono text-2xs ${selectedWeek === w ? 'text-foreground' : 'text-muted-foreground'}`}>
                  Week {i + 1}
                </p>
                <p className="font-mono text-3xs tabular-nums text-foreground-faint">{getWeekLabel(w)}</p>
                {weekTotal > 0 && <p className="mt-0.5 font-mono text-3xs tabular-nums text-foreground-faint">{fmtCOP(weekTotal)}</p>}
              </button>
            )
          })}
        </div>
      </motion.div>

      {/* Summary tiles */}
      <div className="grid grid-cols-2 gap-3 md:grid-cols-4">
        <StatTile label="Items this week" value={log.items.length} icon={<ShoppingCart />} />
        <StatTile label="Week total" value={fmtCOP(weeklyTotal)} icon={<Store />} />
        <StatTile label="Month total" value={fmtCOP(monthlyTotal)} icon={<TrendingUp />} />
        <div
          className="surface cursor-pointer rounded-xl p-4"
          onClick={() => { setEditingBudget(true); setBudgetInput(String(foodBudget)) }}
          title="Synced with the Finances Food budget"
        >
          <p className="font-mono text-2xs uppercase tracking-wider text-muted-foreground">Food budget</p>
          {editingBudget ? (
            <input
              value={budgetInput}
              onChange={(e) => setBudgetInput(e.target.value.replace(/\D/g, ''))}
              onKeyDown={(e) => { if (e.key === 'Enter') { const v = Number(budgetInput) || 0; setFinances(prev => withFoodBudget(prev, viewMonth, v)); setBudget(() => v || 646000); setEditingBudget(false) } }}
              onBlur={() => { const v = Number(budgetInput) || 0; setFinances(prev => withFoodBudget(prev, viewMonth, v)); setBudget(() => v || 646000); setEditingBudget(false) }}
              className="mt-1.5 w-full border-b border-input bg-transparent font-mono text-2xl font-medium tabular-nums text-foreground"
              autoFocus
              onClick={(e) => e.stopPropagation()}
            />
          ) : (
            <p className="mt-1.5 font-mono text-2xl font-medium leading-none tabular-nums text-foreground">{fmtCOP(foodBudget)}</p>
          )}
          <p className={`mt-1.5 font-mono text-2xs tabular-nums ${monthlyTotal <= foodBudget ? 'text-success' : 'text-destructive'}`}>
            {monthlyTotal <= foodBudget ? `${fmtCOP(foodBudget - monthlyTotal)} left` : `Over by ${fmtCOP(monthlyTotal - foodBudget)}`}
          </p>
        </div>
      </div>

      {/* Suggested shopping list (populated by an MCP tool) */}
      <WidgetCard title="Shopping List" compact delay={0.03}>
        {!marketList || marketList.items.length === 0 ? (
          <EmptyState
            message="No list yet."
            hint="Ask Claude to build one from your previous buys."
            className="py-4"
          />
        ) : (
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <span className="font-mono text-2xs tabular-nums text-foreground-faint">
                {marketList.generatedAt ? `Generated ${fmtRelDate(marketList.generatedAt)}` : ''}
                {typeof marketList.weeksAnalyzed === 'number' ? ` · ${marketList.weeksAnalyzed}w analyzed` : ''}
              </span>
              <Button
                variant="ghost"
                size="xs"
                onClick={clearMarketList}
                className="text-foreground-faint hover:text-destructive"
              >
                Clear
              </Button>
            </div>
            {marketList.items.map((li, i) => (
              <div
                key={`${li.name}-${i}`}
                className="flex items-center justify-between gap-2 border-t border-border/60 pt-2 text-xs first:border-t-0 first:pt-0"
              >
                <div className="flex min-w-0 items-center gap-2">
                  <button
                    onClick={() => toggleListItem(i)}
                    className="shrink-0"
                    aria-label={li.checked ? `Uncheck ${li.name}` : `Check off ${li.name}`}
                  >
                    {li.checked
                      ? <CheckSquare className="h-4 w-4 text-success" />
                      : <Square className="h-4 w-4 text-foreground-faint" />}
                  </button>
                  <span className={`truncate ${li.checked ? 'text-foreground-faint line-through' : 'text-foreground'}`}>
                    {li.name}
                  </span>
                  <span className="shrink-0 font-mono tabular-nums text-foreground-faint">{li.quantity} · {fmtFull(li.price)}</span>
                </div>
                <div className="flex shrink-0 items-center gap-2">
                  <Chip size="sm" className="hidden sm:inline-flex">{li.store}</Chip>
                  <Chip size="sm" className="hidden sm:inline-flex">{li.category}</Chip>
                  {typeof li.timesBought === 'number' && li.timesBought > 0 && (
                    <span className="font-mono text-2xs tabular-nums text-foreground-faint">{li.timesBought}x</span>
                  )}
                  <Button
                    variant="secondary"
                    size="icon-sm"
                    onClick={() => addListItemToWeek(i)}
                    aria-label={`Add ${li.name} to this week`}
                  >
                    <Plus />
                  </Button>
                </div>
              </div>
            ))}
          </div>
        )}
      </WidgetCard>

      {/* Quick Add */}
      <div className="surface space-y-3 rounded-xl p-4">
        <div className="flex items-center justify-between">
          <Button
            variant="ghost"
            size="xs"
            onClick={() => setShowQuickAdd(!showQuickAdd)}
            className="-ml-2 font-mono text-2xs uppercase tracking-wider text-muted-foreground"
            aria-expanded={showQuickAdd}
          >
            Quick Add
            <ChevronDown className={`transition-transform ${showQuickAdd ? 'rotate-180' : ''}`} />
          </Button>
          {showQuickAdd && (
            <Button
              variant={editingPresets ? 'secondary' : 'ghost'}
              size="icon-xs"
              onClick={() => setEditingPresets(!editingPresets)}
              aria-label={editingPresets ? 'Done editing presets' : 'Edit presets'}
            >
              <Pencil />
            </Button>
          )}
        </div>
        {showQuickAdd && (
          <>
            <div className="grid grid-cols-2 gap-2 sm:flex sm:flex-wrap sm:gap-1.5">
              {presets.map((preset, i) => (
                <div key={`${preset.name}-${i}`} className="group relative">
                  <button
                    onClick={() => !editingPresets && quickAddItem(preset)}
                    className={`w-full rounded-md border border-border bg-muted/40 px-3 py-2.5 text-left text-xs transition-colors sm:px-2.5 sm:py-1.5 ${
                      editingPresets ? 'cursor-default pr-7' : 'hover:bg-muted/70 active:bg-muted'
                    }`}
                  >
                    <span className="text-foreground">{preset.name}</span>
                    <span className="ml-1 font-mono text-2xs tabular-nums text-foreground-faint">{fmtCOP(preset.price)}</span>
                  </button>
                  {editingPresets && (
                    <Button
                      variant="destructive"
                      size="icon-xs"
                      className="absolute -right-1.5 -top-1.5 h-5 w-5 rounded-full"
                      onClick={() => removePreset(i)}
                      aria-label={`Remove preset ${preset.name}`}
                    >
                      <X />
                    </Button>
                  )}
                </div>
              ))}
            </div>
            {/* Custom preset form */}
            <div className="flex flex-wrap items-end gap-2">
              <Input placeholder="Name" value={newPresetName} onChange={(e) => setNewPresetName(e.target.value)}
                className="h-8 min-w-[120px] flex-1 text-xs" />
              <Input type="number" placeholder="Price" value={newPresetPrice} onChange={(e) => setNewPresetPrice(e.target.value)}
                className="h-8 w-20 text-xs" />
              <select value={newPresetStore} onChange={(e) => setNewPresetStore(e.target.value)}
                className="h-8 rounded-md border border-input bg-background px-2 text-xs text-foreground">
                {STORES.map(s => <option key={s} value={s}>{s}</option>)}
              </select>
              <select value={newPresetCategory} onChange={(e) => setNewPresetCategory(e.target.value)}
                className="h-8 rounded-md border border-input bg-background px-2 text-xs text-foreground">
                {CATEGORIES.map(c => <option key={c} value={c}>{c}</option>)}
              </select>
              <Button variant="secondary" size="icon" onClick={saveToPresets} aria-label="Save preset">
                <Bookmark />
              </Button>
            </div>
          </>
        )}
      </div>

      {/* Add item form — only for current or future weeks */}
      <WidgetCard title={`Add Purchase — ${getWeekLabel(selectedWeek)}`} compact delay={0.05}>
        <div className="flex flex-wrap items-end gap-2">
          <div className="min-w-[120px] flex-1">
            <label className="text-2xs text-muted-foreground">Item</label>
            <Input placeholder="Pollo, leche..." value={newName} onChange={(e) => setNewName(e.target.value)} className="h-8 text-xs" onKeyDown={(e) => e.key === 'Enter' && addItem()} />
          </div>
          <div className="w-20">
            <label className="text-2xs text-muted-foreground">Price (COP)</label>
            <Input type="number" placeholder="12000" value={newPrice} onChange={(e) => setNewPrice(e.target.value)} className="h-8 text-xs" onKeyDown={(e) => e.key === 'Enter' && addItem()} />
          </div>
          <div className="w-14">
            <label className="text-2xs text-muted-foreground">Qty</label>
            <Input type="number" value={newQty} onChange={(e) => setNewQty(e.target.value)} className="h-8 text-xs" min={1} />
          </div>
          <div className="w-20">
            <label className="text-2xs text-muted-foreground">Store</label>
            <select value={newStore} onChange={(e) => setNewStore(e.target.value)} className="h-8 w-full rounded-md border border-input bg-background px-2 text-xs text-foreground">
              {STORES.map(s => <option key={s} value={s}>{s}</option>)}
            </select>
          </div>
          <div className="w-20">
            <label className="text-2xs text-muted-foreground">Category</label>
            <select value={newCategory} onChange={(e) => setNewCategory(e.target.value)} className="h-8 w-full rounded-md border border-input bg-background px-2 text-xs text-foreground">
              {CATEGORIES.map(c => <option key={c} value={c}>{c}</option>)}
            </select>
          </div>
          <Button variant="secondary" size="sm" className="h-8 shrink-0" onClick={addItem} aria-label="Add purchase">
            <Plus />
          </Button>
        </div>
      </WidgetCard>

      {/* Items list */}
      {log.items.length > 0 ? (
        <WidgetCard title={`Purchases — ${getWeekLabel(selectedWeek)}`} compact delay={0.1}>
          <div className="overflow-x-auto">
            <table className="w-full text-xs">
              <thead>
                <tr className="font-mono text-2xs uppercase tracking-wider text-muted-foreground">
                  <th className="pb-2 text-left font-medium">Item</th>
                  <th className="w-16 pb-2 text-left font-medium">Store</th>
                  <th className="w-16 pb-2 text-left font-medium">Category</th>
                  <th className="w-16 pb-2 text-right font-medium">Price</th>
                  <th className="w-10 pb-2 text-right font-medium">Qty</th>
                  <th className="w-16 pb-2 text-right font-medium">Total</th>
                  <th className="w-8 pb-2"></th>
                </tr>
              </thead>
              <tbody>
                {log.items.map((item) => (
                  <tr key={item.id} className="group border-t border-border/60">
                    <td className="py-1.5 text-foreground">{item.name}</td>
                    <td className="py-1.5 text-muted-foreground">{item.store}</td>
                    <td className="py-1.5 text-muted-foreground">{item.category}</td>
                    <td className="py-1.5 text-right font-mono tabular-nums text-muted-foreground">{fmtFull(item.price)}</td>
                    <td className="py-1.5 text-right font-mono tabular-nums text-muted-foreground">{item.quantity}</td>
                    <td className="py-1.5 text-right font-mono font-medium tabular-nums text-foreground">{fmtFull(item.price * item.quantity)}</td>
                    <td className="py-1.5 text-right">
                      <Button
                        variant="ghost"
                        size="icon-xs"
                        onClick={() => removeItem(item.id)}
                        aria-label={`Remove ${item.name}`}
                        className="text-muted-foreground opacity-0 hover:text-destructive focus-visible:opacity-100 group-hover:opacity-100"
                      >
                        <Trash2 />
                      </Button>
                    </td>
                  </tr>
                ))}
                <tr className="border-t border-border/50 font-medium">
                  <td colSpan={5} className="py-2 text-muted-foreground">Total</td>
                  <td className="py-2 text-right font-mono tabular-nums">{fmtFull(weeklyTotal)}</td>
                  <td></td>
                </tr>
              </tbody>
            </table>
          </div>
        </WidgetCard>
      ) : (
        <EmptyState message="No purchases logged for this week." />
      )}

      {/* Breakdown */}
      {log.items.length > 0 && (
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
          <WidgetCard title="By Store" compact delay={0.15}>
            <div className="space-y-2">
              {byStore.map(([store, total]) => (
                <div key={store} className="flex items-center justify-between text-xs">
                  <span className="text-foreground">{store}</span>
                  <div className="flex items-center gap-2">
                    <div className="h-1 w-24 rounded-full bg-muted/60">
                      <div className="h-full rounded-full bg-foreground/40" style={{ width: `${(total / weeklyTotal) * 100}%` }} />
                    </div>
                    <span className="w-14 text-right font-mono tabular-nums text-muted-foreground">{fmtCOP(total)}</span>
                  </div>
                </div>
              ))}
            </div>
          </WidgetCard>

          <WidgetCard title="By Category" compact delay={0.2}>
            <div className="space-y-2">
              {byCategory.map(([cat, total]) => (
                <div key={cat} className="flex items-center justify-between text-xs">
                  <span className="text-foreground">{cat}</span>
                  <div className="flex items-center gap-2">
                    <div className="h-1 w-24 rounded-full bg-muted/60">
                      <div className="h-full rounded-full bg-foreground/40" style={{ width: `${(total / weeklyTotal) * 100}%` }} />
                    </div>
                    <span className="w-14 text-right font-mono tabular-nums text-muted-foreground">{fmtCOP(total)}</span>
                  </div>
                </div>
              ))}
            </div>
          </WidgetCard>
        </div>
      )}
    </div>
  )
}
