import { test, expect, mockStores } from './fixtures'
import { applyCreditCardCommand, emptyCreditCardState } from '../electron/credit-card-model'
import type { CreditCardState } from '../electron/credit-card-types'

const syntheticCard = () => applyCreditCardCommand(emptyCreditCardState(), {
  type: 'initialize', requestId: 'synthetic-setup', card: { id: 'card', name: 'Everyday card', limit: 500000, closingDay: 4, dueDay: 24 },
  purchases: [{ id: 'desk', name: 'Desk lamp', amount: 120001, installments: 3, firstDueDate: '2026-11-24', status: 'pending' }],
  snapshot: { id: 'bank', observedDate: '2026-10-03', reportedDebt: 0, availableCredit: 379999 },
}, '2026-10-03T14:00:00Z')
const finance = { year: 2026, items: [
  { id: 'salary', name: 'Salary', type: 'Income', months: Array(12).fill(500000) },
  { id: 'rent', name: 'Rent', type: 'Expense', category: 'Home', months: Array(12).fill(100000) },
] }
const cardSection = (page: import('@playwright/test').Page) => page.locator('#credit-card')
const cardScreenshot = async (page: import('@playwright/test').Page, name: string) => {
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await cardSection(page).evaluate((element) => element.scrollIntoView({ block: 'start' }))
  await page.screenshot({ path: `.private/credit-card/${name}.png`, animations: 'disabled' })
}

for (const width of [320, 1440]) {
  test(`Budget jump skips the card workspace at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 800 })
    await mockStores(page, { 'cortex-credit-card': syntheticCard(), 'cortex-finances': finance })
    await page.goto('/#/finance')
    const jump = page.getByRole('button', { name: 'Budget', exact: true })
    await expect(jump).toBeInViewport()
    await expect(page.getByRole('heading', { name: 'Budget', exact: true })).not.toBeInViewport()
    await jump.click()
    await expect(page.getByRole('heading', { name: 'Budget', exact: true })).toBeInViewport()
    await expect(page.getByRole('button', { name: 'Set paid amount for Rent' })).toBeInViewport()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  })
}

test('preview writes nothing, saves known charges atomically, and preserves cross-year installments', async ({ page }) => {
  await page.clock.setFixedTime(new Date('2026-10-03T15:00:00Z'))
  await page.setViewportSize({ width: 1440, height: 1000 })
  const backend = await mockStores(page, { 'cortex-credit-card': syntheticCard(), 'cortex-finances': finance })
  await page.goto('/#/finance')
  const section = cardSection(page)
  await expect(section.getByText('November 2026', { exact: true })).toBeVisible()
  await expect(section.getByText('January 2027', { exact: true })).toBeVisible()
  await expect(section.getByText('Last reported debt').locator('..')).toContainText('$0')
  await page.getByRole('button', { name: 'Add purchase' }).click()
  await page.getByLabel('Purchase name', { exact: true }).fill('Headphones')
  await page.getByLabel('Purchase amount (COP)', { exact: true }).fill('60000')
  await page.getByLabel('Installments', { exact: true }).fill('2')
  await page.getByLabel('First due date', { exact: true }).fill('2026-12-15')
  await page.getByLabel('Known first-cycle interest (COP)').fill('700')
  await page.getByLabel('Known first-cycle fees (COP)').fill('0')
  await page.getByRole('button', { name: 'Preview purchase', exact: true }).click()
  await expect(page.getByText('Unsaved preview')).toBeVisible()
  await expect(page.getByRole('dialog')).toContainText('$70.700')
  expect(backend.cardCommands).toHaveLength(0)
  expect((backend.stores['cortex-credit-card'] as CreditCardState).purchases).toHaveLength(1)
  await page.getByRole('button', { name: 'Save purchase', exact: true }).click()
  await expect.poll(() => backend.cardCommands.length).toBe(1)
  const state = backend.stores['cortex-credit-card'] as CreditCardState
  expect(state.purchases.find((purchase) => purchase.name === 'Headphones')?.purchaseDate).toBeUndefined()
  expect(state.cycles).toMatchObject([{ id: '2026-12', interest: 700, fees: 0, chargesConfirmed: true }])
  await page.getByRole('button', { name: 'Edit purchase Headphones' }).click()
  await page.getByLabel('Purchase status').selectOption('posted')
  await page.getByRole('button', { name: 'Save purchase', exact: true }).click()
  await expect.poll(() => (backend.stores['cortex-credit-card'] as CreditCardState).purchases.find((purchase) => purchase.name === 'Headphones')?.status).toBe('posted')
  await page.getByRole('button', { name: 'Cancel purchase Headphones' }).click()
  await expect.poll(() => (backend.stores['cortex-credit-card'] as CreditCardState).purchases.find((purchase) => purchase.name === 'Headphones')?.status).toBe('cancelled')
  await page.getByRole('button', { name: 'Update bank snapshot' }).click()
  await page.getByLabel('Bank reported debt (COP)').fill('3000')
  await page.getByLabel('Bank available credit (COP)').fill('400000')
  await page.getByRole('button', { name: 'Save bank snapshot' }).click()
  await expect(section.getByText('Last reported debt').locator('..')).toContainText('$3.000')
  expect((backend.stores['cortex-credit-card'] as CreditCardState).snapshots.find((snapshot) => snapshot.id === 'bank')?.reportedDebt).toBe(0)
  await cardScreenshot(page, 'desktop-ui')
})

test('partial early payment debits cash once, set-aside stays preparation, and corrections retain history', async ({ page }) => {
  await page.clock.setFixedTime(new Date('2026-10-03T15:00:00Z'))
  const backend = await mockStores(page, { 'cortex-credit-card': syntheticCard(), 'cortex-finances': finance })
  await page.goto('/#/finance')
  await page.getByRole('button', { name: 'Record payment', exact: true }).click()
  await page.getByLabel('Actual payment amount (COP)').fill('10000')
  await expect(page.getByLabel('Allocated amount (COP)')).toHaveValue('10000')
  await page.getByRole('button', { name: 'Save card payment' }).click()
  await expect.poll(() => (backend.stores['cortex-credit-card'] as CreditCardState).payments.length).toBe(1)
  const payment = (backend.stores['cortex-credit-card'] as CreditCardState).payments[0]
  expect(payment).toMatchObject({ amount: 10000, paidDate: '2026-10-03', allocations: [{ cycleId: '2026-11', amount: 10000 }] })
  expect(payment.allocations[0].principal).toBeUndefined()
  await expect(page.getByText('Account Balance · Oct').locator('..').locator('..')).toContainText('$490.000')
  await page.getByRole('tab', { name: 'Nov', exact: true }).click()
  await expect(page.getByText('Expenses', { exact: true }).first().locator('..').locator('..')).toContainText('$140K')
  await expect(page.getByText('Pending', { exact: true }).first().locator('..').locator('..')).toContainText('$130.000')
  await page.getByRole('button', { name: 'Set aside', exact: true }).click()
  await page.getByLabel('Money set aside (COP)').fill('30000')
  await page.getByRole('button', { name: 'Save preparation' }).click()
  await expect(cardSection(page).getByText('Ready to pay', { exact: true })).toBeVisible()
  await expect(page.getByText('Account Balance · Nov').locator('..').locator('..')).toContainText('$500.000')
  await page.getByRole('button', { name: 'Statement checkpoint', exact: true }).click()
  await page.getByLabel('Bank minimum (COP)').fill('5000')
  await page.getByLabel('Chosen payment target (COP)').fill('40000')
  await page.getByLabel('Statement interest (COP)').fill('0')
  await page.getByLabel('Statement fees (COP)').fill('0')
  await page.getByLabel('I checked these figures against the bank statement').check()
  await page.getByRole('button', { name: 'Save statement' }).click()
  await expect(cardSection(page)).toContainText('Bank minimum $5.000 · Planned installments $40.000')
  await cardSection(page).getByRole('tab', { name: 'Payment history' }).click()
  await page.getByRole('button', { name: 'Correct payment of $10.000 on Oct 3, 2026' }).click()
  await page.getByLabel('Actual payment amount (COP)').fill('12000')
  await page.getByLabel('Allocated amount (COP)').fill('12000')
  await page.getByRole('button', { name: 'Save payment correction' }).click()
  await expect.poll(() => (backend.stores['cortex-credit-card'] as CreditCardState).payments[0].amount).toBe(12000)
  await page.getByRole('button', { name: 'Void payment of $12.000 on Oct 3, 2026' }).click()
  await page.getByLabel('Reason for voiding').fill('Bank reversed the transfer')
  await page.getByRole('button', { name: 'Void payment', exact: true }).click()
  await expect.poll(() => (backend.stores['cortex-credit-card'] as CreditCardState).payments[0].status).toBe('voided')
  expect((backend.stores['cortex-credit-card'] as CreditCardState).audit.some((entry) => entry.type === 'payment.save' && entry.previous)).toBe(true)
})

test('empty setup, keyboard forms, reminder tests and mobile layout work at 320px', async ({ page }) => {
  await page.clock.setFixedTime(new Date('2026-10-03T15:00:00Z'))
  await page.addInitScript(() => localStorage.setItem('cortex-ui-theme', 'light'))
  await page.setViewportSize({ width: 320, height: 800 })
  const backend = await mockStores(page, { 'cortex-finances': finance })
  await page.goto('/#/finance')
  await page.getByRole('button', { name: 'Set up credit card' }).click()
  await page.getByLabel('Card name').fill('Travel card')
  await page.getByLabel('Card name').press('Tab')
  await expect(page.getByLabel('Credit limit (COP)')).toBeFocused()
  await page.getByLabel('Credit limit (COP)').fill('300000')
  await page.getByLabel('Due day').press('Enter')
  await expect(cardSection(page)).toContainText('Travel card')
  await expect(cardSection(page)).toContainText('No card purchases yet.')
  await page.getByRole('button', { name: 'Add purchase' }).click()
  await page.getByLabel('Purchase name', { exact: true }).fill('Train ticket')
  await page.getByLabel('Purchase amount (COP)', { exact: true }).fill('60000')
  await page.getByLabel('First due date').fill('2026-11-24')
  await page.getByRole('button', { name: 'Save purchase', exact: true }).click()
  await expect(cardSection(page)).toContainText('Train ticket')
  await page.getByRole('button', { name: 'Reminders', exact: true }).click()
  await page.getByRole('button', { name: 'Test phone' }).click()
  await expect(page.getByRole('status')).toContainText('Provider accepted; check your phone for display')
  expect(backend.cardTests).toEqual(['phone'])
  await page.getByLabel('Launch Cortex at login', { exact: true }).check()
  await page.getByLabel('Days before payment').fill('7, 2, 1')
  await page.getByRole('button', { name: 'Save reminders' }).click()
  await expect.poll(() => (backend.stores['cortex-credit-card'] as CreditCardState).reminders.leadDays).toEqual([7, 2, 1])
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await cardScreenshot(page, 'mobile-ui')
  const light = await cardSection(page).getByRole('heading', { name: 'Committed on your card' }).locator('..').locator('..').evaluate((element) => getComputedStyle(element).color)
  await page.evaluate(() => { document.documentElement.classList.add('dark'); document.documentElement.dataset.theme = 'dark' })
  await cardScreenshot(page, 'mobile-dark-ui')
  expect(await cardSection(page).getByRole('heading', { name: 'Committed on your card' }).locator('..').locator('..').evaluate((element) => getComputedStyle(element).color)).not.toBe(light)
})

test('Home attention opens Finance and a rejected command leaves the draft reviewable', async ({ page }) => {
  await page.clock.setFixedTime(new Date('2026-11-17T15:00:00Z'))
  await mockStores(page, { 'cortex-credit-card': syntheticCard(), 'cortex-finances': finance })
  await page.goto('/#/')
  await expect(page.getByRole('heading', { name: 'Needs attention · Credit card' })).toBeVisible()
  await page.getByRole('button', { name: 'Open Credit card' }).click()
  await expect(cardSection(page)).toBeVisible()
  await expect(cardSection(page).getByRole('heading', { name: 'Credit card', exact: true })).toBeInViewport()
  await page.route('**/api/credit-card/command', (route) => route.fulfill({ json: { ok: false, error: 'Ledger could not be saved' } }))
  await page.getByRole('button', { name: 'Add purchase' }).click()
  await page.getByLabel('Purchase name', { exact: true }).fill('Speaker')
  await page.getByLabel('Purchase amount (COP)', { exact: true }).fill('50000')
  await page.getByRole('button', { name: 'Save purchase', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Ledger could not be saved')
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.getByLabel('Purchase name', { exact: true })).toHaveValue('Speaker')
})
